package it.thedarksword.essentialsvc.objets;

public enum ConfigMessage {

    INSUFFICIENT_PERMISSION,
    INVALID_ARGUMENTS,
    PLAYER_NOT_FOUND,
    TP,
    TPA_SENT,
    TPA_REQUEST,
    NO_TPA_TO_ACCEPT,
    TPA_ACCEPT,
    TPA_ACCEPTED,
    TP_DENY,
    TPA_CANCELLED,
    TELEPORTING,
    SPAWN_SET,
    SPAWN_NOT_SET,
    SPAWN,
    CANT_BACK,
    BACK,
    MAX_HOMES,
    NO_HOME_NAME,
    HOME_SET,
    HOME_REMOVED,
    HOME_LIST,
    HOME,
    GAMEMODE,
    GOD,
    FLY,
    CANT_INVSEE,
    REPAIR_FAILED,
    REPAIR,
    HELPOP,
    MESSAGE_FROM,
    MESSAGE_TO,
    NICKNAME;
}
